use_frameworks!

platform :ios, '10.0'

target 'Xlightweight-Store-iOS_Example' do
  pod 'Xlightweight-Store-iOS', :path => '../'

  target 'Xlightweight-Store-iOS_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
